### PR TITLE
feat: Added the option to ignore files and folders via settings

### PR DESCRIPTION
**Pull request by niposch**
I added a text field in the settings where globs can be put into.
If any of these match a file, it will be ignored and therefore not be scanned.

This feature is especially useful when using this plugin in combination with the obsidian-excalidraw-plugin because this plugin stores its files as .excalidraw.md.
This will cause the Obsidian_to_Anki plugin to scan these files. Excessive scan times are caused by scanning these large files.
Adding `**/*.excalidraw.md` to the ignore option will alleviate this problem because these files will be ignored.
It could also be useful if a user wishes a specific folder not to be scanned (f.e. the template folder)
The option I added should behave like a git ignore file which is documented here: https://git-scm.com/docs/gitignore

### CODE REVIEW

**Comment by ananthuthilakan** [comment]
kindly update

**Comment by ananthuthilakan** [comment]
it looks like author is away since December 2020😥

**Comment by makrs11** [comment]
If somebody else is looking for a solution to use Obsidian to Anki with Ecalidraw:
Just activate the compression function in the Excalidraw options. In my case this changes the filetype from .excalidraw.md to .excalidraw and stops Anki from searching these files and freezing in the process.
grafik

**Comment by manderson21** [comment]
@Pseudonium Is there any chance we could get this feature merged? There are conflicts that I'd be willing to look into resolving, but since this PR is so old I'd like to get some confirmation on whether it has a chance of being merged back?

**Comment by MisterPresident** [comment]
Maybe we should think about a maintained fork.
Whenever @Pseudonium comes back we could merge it back.

**Comment by manderson21** [comment]
@MisterPresident I was thinking about that myself. One of the worst things about such impactful open-source projects like this, is they tend to succumb to Bus Factor one day. Many good obsidian plugins especially have. It's really important for project owners to find a few contributors to give write access to so the project can continue without you. But at least there is a LICENSE file. So separately maintained forks can be used for distribution.

**Comment by niposch** [comment]
Having this plugin unmaintained is really looming over the prospects of obsidian for me. Sure obsidian is a good note-taking app but with this plugin it's an awesome note-taking app.

I'd be willing to help out maintaining a fork. We can do it on https://github.com/niposch/Obsidian_to_Anki_Reloaded
I renamed the fork, (not sure if the name is still too similar though). Over the coming days, I'll have a look at merging this PR into my fork's master branch and getting a convenient way for people to install the plugin set up. Maybe BRAT is an option, or maybe even publish the fork to the obsidian plugin store.
I'll have a look at the other open PRs and see if there is anything else that would be worth it to integrate into the fork.
I guess publishing the fork is only really valuable once we get a few new features/bug fixes in there.

**Comment by ShootingKing-AM** [comment]
Can you rebase this PR and add some Tests ? Do take note of this feature (https://github.com/ShootingKing-AM/Obsidian_to_Anki/pull/154)

**Comment by ShootingKing-AM** [comment]
Are you done @niposch ? Can you add some information about this feature and how to use in Readme.MD. Also since we already know that excalidraw, Templater obsidian addons can you set the default setting to ignore this file.

It would be also awesome if you can do a hyperlink some example so that a common (non-developer) can understand how to use globs (dont specify .gitignore :) ). Also you can have some examples as placeholder text, like "ignore_this_file.md\nignore_this_dir/*" so that it will be easy for common users to understand. 

Let me know when you are done, want to merge this feature as soon as possible :)

**Comment by niposch** [comment]
I'm done. Added a bit more documentation and a default value for the setting.
I haven't figured out what to do about ignoring the template folder as there isn't any default template folder name I'm aware of. Maybe we could add `*[Tt]emplate*/**` but that could also be error prone.

**Comment by ShootingKing-AM** [comment]
Seems like some tests are failing - https://github.com/Pseudonium/Obsidian_to_Anki/actions/runs/7627084329/job/20774950101?pr=503#step:7:9685

**Comment by ShootingKing-AM** [comment]
still you can find the failed tests here #503

**Pull request merged**
