### PR TITLE
Fix #409

### LINKED ISSUE #409: Cannot scan vault: TypeError: Cannot read properties of null (reading 'hasOwnProperty')
Environment : obsidian 1.1.12; anki 2.1.56
After setting up obsidian to anki and trying to scan the vault, I get the following message in the vault

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'hasOwnProperty')
at FileManager.getFolderPathList (plugin:obsidian-to-anki-plugin:30603:29 )
at FileManager.dataToFileData (plugin:obsidian-to-anki-plugin:30634:39)
at FileManager.genAllFiles (plugin:obsidian-to-anki-plugin:30651:36)
at async FileManager.initialiseFiles (plugin:obsidian-to -anki-plugin:30656:9)
at async MyPlugin.scanVault (plugin:obsidian-to-anki-plugin:30958:9)
at async HTMLDivElement.eval (plugin:obsidian-to-anki-plugin:30995:13)

Screenshot 2023-02-23 at 18 59 18

EDIT:
I looked around on the internet and found this (thank you google translate lol)

https://forum-zh.obsidian.md/t/topic/14838

The fix the guy suggests actually works.

### PR DESCRIPTION
**Pull request by ShootingKing-AM**
Suggested fix to Issue #409

### CODE REVIEW

**Comment by Ali-C-Ila** [comment]
Thanks for this! 
However, as the auther of this plugin @Pseudonium has gone dark for over two years, I find it unlikely that this will ever get merged.
I sincerely wish that if you (or anyone) have the passion for it, you can fork and maintain the code in the future.

**Comment by ShootingKing-AM** [comment]
> Thanks for this! However, as the auther of this plugin @Pseudonium has gone dark for over two years, I find it unlikely that this will ever get merged. I sincerely wish that if you (or anyone) have the passion for it, you can fork and maintain the code in the future.

Ok, i made a release for this fix in my fork is you are interested. Added CI as well.
https://github.com/ShootingKing-AM/Obsidian_to_Anki/releases/tag/3.4.2

Maybe I will push all the changes on my fork onto this (CI and CodeQl changes) when pseudo is back

**Comment by shoudeyunkaijianyueming** [comment]
Want to add folders that exclude synchronization, similar to this branch
https://github.com/aviral-batra/Obsidian_to_Anki

**Comment by shoudeyunkaijianyueming** [comment]
At the same time, is it possible to increase the function of reverse synchronization from anki to obsidian, thank you, there is currently no.

**Comment by ShootingKing-AM** [comment]
> At the same time, is it possible to increase the function of reverse synchronization from anki to obsidian, thank you, there is currently no.

Umm.. this PR is related to only to the fix mentioned. Yes its possible to increase reverse sync function, maybe you can open a new issue in my fork ? and maybe we can request @aviral-batra to make a PR to my fork ?

**Comment by shoudeyunkaijianyueming** [comment]
> > At the same time, is it possible to increase the function of reverse synchronization from anki to obsidian, thank you, there is currently no.
> 
> Umm.. this PR is related to only to the fix mentioned. Yes its possible to increase reverse sync function, maybe you can open a new issue in my fork ? and maybe we can request @aviral-batra to make a PR to my fork ?
Ok, I raised the question under your issues, it's my reason, I'm a newbie, sorry, the location of the question is wrong, and aviral-batra has not been updated for a long time (although I am using this now, the developer may give up development).

**Comment by shoudeyunkaijianyueming** [comment]
image
I remember, I didn't find the issue location of your copy library at that time.

**Comment by ShootingKing-AM** [comment]
> image
> 
> I remember, I didn't find the issue location of your copy library at that time.

Oops ! I forgot to enable them. You can find them now.
But please note a point, I wish to maintain the addon - meaning if there are any issues with existing functionality like this PR then I would like to fix it.
Sadly, I too, right now, don't have the time to develop it - meaning add newer functionality. But yes Pull requests with new functionality are welcome.

**Comment by Pseudonium** [comment]
Aha, so this is the potential fix... let me take a look through it now

**Comment by Pseudonium** [comment]
Ah, yeah, and sorry for going dark for so long... I guess I got very busy with uni and knew that this code probably had all sorts of bad practices I'd rather not touch with a 10-foot pole. So my attitude kinda became "once I find an issue that starts affecting my workflow, I'll fix it ASAP". I've been using the plugin basically daily anyway so thought that I'd catch one quickly once any cropped up. Though, judging by the fact that this is issue 409, maybe not.

**Comment by aviral-batra** [comment]
> reason, I'm a newbie, sorry, the location of the question is wrong, and aviral-batra has not been updated for a long time (

Hi sorry, I haven't used obsidian to anki for a while but I re-opened my pull request with all of the updates that I made based on a bunch of pull requests. What was your question exactly I'm not sure I understand?

**Comment by ShootingKing-AM** [comment]
Heyyy @Pseudonium !! Atlast you are back now :3 yeah uni times are busy times :3
Good to have you back :3 Did you get my mail ?

**Comment by aviral-batra** [comment]
> Heyyy @Pseudonium !! Atlast you are back now :3 yeah uni times are busy times :3 Good to have you back :3 Did you get my mail ?
> 
> As a proof of this working i have implemented e2e tests for all features. You can check the results here : [ShootingKing-AM#52](https://github.com/ShootingKing-AM/Obsidian_to_Anki/pull/52) ([ShootingKing-AM#52 (comment)](https://github.com/ShootingKing-AM/Obsidian_to_Anki/pull/52#issuecomment-1477084467))

Did you want me to open a pull req to your repo for my changes?

**Comment by Pseudonium** [comment]
Ah, so it was you who wrote the email! I haven't got a chance to read it as of yet..

So here's what I'm thinking - for now, I just wanna make as minimal changes to the codebase as possible, so I guess I can just pull this in, and then make a new release etc.

**Comment by ShootingKing-AM** [comment]
> > Heyyy @Pseudonium !! Atlast you are back now :3 yeah uni times are busy times :3 Good to have you back :3 Did you get my mail ?
> > As a proof of this working i have implemented e2e tests for all features. You can check the results here : [ShootingKing-AM#52](https://github.com/ShootingKing-AM/Obsidian_to_Anki/pull/52) ([ShootingKing-AM#52 (comment)](https://github.com/ShootingKing-AM/Obsidian_to_Anki/pull/52#issuecomment-1477084467))
> 
> Did you want me to open a pull req to your repo for my changes?

Yes. but not now, since @Pseudonium is back, you can tidy up your PR right here.


> Ah, so it was you who wrote the email! I haven't got a chance to read it as of yet..
> 
Yup 😁

> So here's what I'm thinking - for now, I just wanna make as minimal changes to the codebase as possible, so I guess I can just pull this in, and then make a new release etc.

Yup but CI is going to fail i guess.

**Comment by Pseudonium** [comment]
Ah, ok, so what specifically would fail?

**Comment by ShootingKing-AM** [comment]
> Ah, ok, so what specifically would fail?

#412

**Comment by Pseudonium** [comment]
Ok, so that's good now, at least. Anything else I should do before the release?

**Comment by ShootingKing-AM** [comment]
Good for now. You can release a minor version now :)

**Pull request merged**
