### PR TITLE
fix: Bug obsidian tags not being added for regex notes

### LINKED ISSUE #196: Tags do not get into Anki when using QA-style regex
I've tried to specify tags in all ways I could imagine, but they still don't get into the DB.
I'm using the custom regex from [this](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Question-answer-style) wiki-page.
But the standard block style and [markdown table style](https://github.com/Pseudonium/Obsidian_to_Anki/wiki/Markdown-table-style) work fine.

Maybe I'm missing something. Could you advise me on what to do next?

```markdown
#tag1
Q: question2 #tag2
A: answer2 #tag3
<!--ID: 1610066316321-->


Tags: tag21 tag22

---
```

image

### LINKED ISSUE #440: Could not create Neuracache flashcard with tags
Hi, thank you a million for this wonderful plugin. I wonder how to interpret tags in Obsidian note by creating a Neuracache flashcard

So I have turn on "Add Obsidian Tags", and take my note as follows:

```
do a multi-line question #flashcard
You just need to make sure both
the question and answer are one paragraph. #products 
Tags: products 
```

So there are two styles of tags, one by #, another by Tags:

But both don't work in Anki. They are still in the note instead of a tag.

Could you please kindly instruct how to do it? Thank you very much

### PR DESCRIPTION
**Pull request by st3v3nmw**
This should fix #196 where Obsidian tags in regex notes aren't added to Anki.

### CODE REVIEW

**Comment by dummifiedme** [comment]
Is this included in the current version? @st3v3nmw .
If not, how can I manually fix it?
I checked the code, it seems to be the same. But my tags aren't getting picked

**Comment by st3v3nmw** [comment]
It's not currently included.
To manually fix it, clone this repository, install NodeJS, and run `npm i` inside the folder.
Then run `npm run dev` to compile `main.ts` to `main.js`. Then replace the `main.js` file in the plugin's folder in `.obsidian/plugins`.

**Comment by dummifiedme** [comment]
> To manually fix it, clone my fork of this repository, install NodeJS, and run `npm i` inside the folder.

```
npm WARN tarball tarball data for obsidian@https://github.com/obsidianmd/obsidian-api/tarball/master (sha512-OGZPxkzYJ1Lgjd4f7eaBFr8KqIG8vkwVcOblH5BMSIoMieY1NmXL9/ouVwMjc1NJH7ZN6Zi7Qclz8Y42fd8rwQ==) seems to be corrupted. Trying one more time.
npm ERR! code EINTEGRITY
npm ERR! sha512-OGZPxkzYJ1Lgjd4f7eaBFr8KqIG8vkwVcOblH5BMSIoMieY1NmXL9/ouVwMjc1NJH7ZN6Zi7Qclz8Y42fd8rwQ== integrity checksum failed when using sha512: wanted sha512-OGZPxkzYJ1Lgjd4f7eaBFr8KqIG8vkwVcOblH5BMSIoMieY1NmXL9/ouVwMjc1NJH7ZN6Zi7Qclz8Y42fd8rwQ== but got sha512-09/Zpb7sXE264OLk3DDbieU895d6NaNIIL8eyKR+5WpXPSYKeDfwy4yQh3WSb6KHWTJpbyvqUDchh8Yy4lHiRQ==. (15583 bytes)

```

Also, will I lose the settings of the plugin if I make a complete change in the plugin folder?

Can't I just fix the part where you have modified the code?

From comparison, I could see 2 places where there were a semicolon and has been removed in the new code...

**Comment by st3v3nmw** [comment]
Try deleting the package-lock.json file and try again.

> Also, will I lose the settings of the plugin if I make a complete change in the plugin folder?

No. You'll only change the `main.js` file. The settings are stored in `data.json`.

Also, I've made a release on my fork that you can easily download and use.

**Comment by dummifiedme** [comment]
Thanks!! :)

**Comment by rjbergerud** [comment]
bump - would really love this functionality!

**Comment by ludvigalden** [comment]
Why is this not being merged? Just made a similar pull request (https://github.com/Pseudonium/Obsidian_to_Anki/pull/287) which does not include changes to gitignore or the lockfile, if that's the problem. I closed my pull request because I found out about this one.

**Comment by dummifiedme** [comment]
> Why is this not being merged? Just made a similar pull request (#287) that does not include changes to gitignore or the lockfile, if that's the problem. I closed my pull request because I found out about this one.

Because the developer is away since the last release :)

**Comment by timjden** [comment]
Thanks @st3v3nmw ! This has been most frustrating up until now. Much appreciated.

**Comment by noideahowmuch** [comment]
thanks

**Comment by lsolesen** [comment]
@Pseudonium - is this something that is goint to be implemented soon?

**Comment by ShootingKing-AM** [comment]
E2E tests for this fix are done in #479

**Comment by CCerrer** [comment]
The pull request is merged, why the "Tags" seem to only work on the same line of answer?

I tried the same regex as the issue #196: `^Q: ((?:.+\n)*)\n*A: (.+(?:\n(?:^.{1,3}$|^.{4}(?<!<!--).*))*)`
with the examples:
```md
#tag_up
Q: question 1 #tag_question
A: answer example 1 #tag_answer
#tag_above
<!--ID: 1757264898513-->



Tags: #tag_up
Q: question 2 Tags: #tag_question
A: answer example 2 Tags: #tag_answer
<!--ID: 1757264898508-->

Tags: #tag_above


Tags: #tag_up
Q: question 3 Tags: #tag_question
A: answer example 3 #tag_answer
<!--ID: 1757264907731-->


Tags: #tag_above
```
And got a tag only at the inline example:
image

**Pull request merged**
